name: copy_prod_to_staging
# The following secrets are required on Github:
#   - FLIGHTPATH_URL (URL for the flightpath call excluding trailing slash)
#   - HEROKU_APP_NAME_PRODUCTION (source heroku app name)
#   - HEROKU_APP_NAME_STAGING (destination heroku app name)
#   - FLIGHTPATH_AUTH_KEY (from flightpath)
#   - DEPLOYMENT_KEY (as set on corresponding heroku app env var)
run-name: Copy ${{ secrets.HEROKU_APP_NAME_PRODUCTION }} to ${{ secrets.HEROKU_APP_NAME_STAGING }} by @${{ github.actor }}
on: [workflow_dispatch]
concurrency: staging_environment
jobs:
  run_flightpath:
    runs-on: ubuntu-latest
    steps:
      - name: Install curl, jq
        run: apt-get install -y curl jq
      - name: Send POST request to FlightPath
        run: |
          export JOB_STATUS=$(curl -f -X POST -m 900
          -H "Authorization: Token ${{ secrets.FLIGHTPATH_AUTH_KEY }}" -d "source_key=${{ secrets.DEPLOYMENT_KEY }}&destination_key=${{ secrets.DEPLOYMENT_KEY }}&copy_media=1&from_backup=1"
          "https://${{ secrets.FLIGHTPATH_URL }}/${{ secrets.HEROKU_APP_NAME_PRODUCTION }}/${{ secrets.HEROKU_APP_NAME_STAGING }}/")
          echo $JOB_STATUS
          export JOB_ID=$(echo $JOB_STATUS | jq -r '.job_id')
          echo $JOB_ID
